export const FETCH_REPOSITORIES = 'REPOSITORIES/FETCH_REPOSITORIES'
export const FETCH_REPOSITORIES_SUCCESS = 'REPOSITORIES/FETCH_REPOSITORIES_SUCCESS';
export const FETCH_REPOSITORIES_FAILURE = 'REPOSITORIES/FETCH_REPOSITORIES_FAILURE';